<?php

/**
 * @file
 * Contains reusable_items.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function reusable_items_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the reusable_items module.
    case 'help.page.reusable_items':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function reusable_items_theme() {
  $theme = [];
  $theme['reusable_item'] = [
    'render element' => 'elements',
    'file' => 'reusable_item.page.inc',
    'template' => 'reusable_item',
  ];
  $theme['reusable_item_content_add_list'] = [
    'render element' => 'content',
    'variables' => ['content' => NULL],
    'file' => 'reusable_item.page.inc',
  ];
  return $theme;
}

/**
* Implements hook_theme_suggestions_HOOK().
*/
function reusable_items_theme_suggestions_reusable_item(array $variables) {
  $suggestions = [];
  $entity = $variables['elements']['#reusable_item'];
  $sanitized_view_mode = strtr($variables['elements']['#view_mode'], '.', '_');

  $suggestions[] = 'reusable_item__' . $sanitized_view_mode;
  $suggestions[] = 'reusable_item__' . $entity->bundle();
  $suggestions[] = 'reusable_item__' . $entity->bundle() . '__' . $sanitized_view_mode;
  $suggestions[] = 'reusable_item__' . $entity->id();
  $suggestions[] = 'reusable_item__' . $entity->id() . '__' . $sanitized_view_mode;
  return $suggestions;
}
